---
title: "Solved!"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Solved! Set `dev = "quartz_png"` to override `ragg::agg_png` from pkgdown.

```{r}
knitr::opts_chunk$set(
  #fig.path = "man/figures/README-",
  out.width = "100%",
  fig.width = 4, 
  fig.height = 4,
  dev = "quartz_png"
)

dev.cur()
```


```{r}
library(ggplot2)
```

## Img itself is fine

```{r}
path <- "https://github.com/debruine/imginv/raw/master/inst/f_multi.jpg"
img <- magick::image_read(path)
img
```


```{r}
i <- grid::rasterGrob(img, interpolate = FALSE)
width <- 1350
height <- 1350

d <- data.frame(x = 0, y = 0)
```


## Inverted (in vignette)

```{r}
ggplot() +
  scale_y_reverse() +
  coord_fixed(xlim = c(0, width),
              ylim = c(0, height)) +
  annotation_custom(i, 0, width, -height, 0) +
  geom_point(data = d, aes(x, y), size = 5)

```

## Upright

```{r}
ggplot() +
  #scale_y_reverse() +
  coord_fixed(xlim = c(0, width),
              ylim = c(0, height)) +
  annotation_custom(i, 0, width, height, 0) +
  geom_point(data = d, aes(x, y), size = 5)
```

